name: wallet_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  firebase_ui_auth: ^1.15.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  smooth_page_indicator:
  firebase_auth: ^5.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - icons/bill.png
    - icons/analytics.png
    - icons/atm-card.png
    - icons/card-payment.png
    - icons/send.png
    - icons/user.png
    - icons/moldova.png
    - icons/flutter.png
